src/Entity/SousCategorieProduit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SousCategorieProduitRepository")
 */
class SousCategorieProduit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CategorieProduit", inversedBy="sousCategorieProduits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $CategorieProduit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCategorieProduit(): ?CategorieProduit
    {
        return $this->CategorieProduit;
    }

    public function setCategorieProduit(?CategorieProduit $CategorieProduit): self
    {
        $this->CategorieProduit = $CategorieProduit;

        return $this;
    }


}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\CategorieProduit;
use App\Entity\Produit;
use App\Entity\SousCategorieProduit;
use App\Entity\UtilisateurAdministration;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\File;

class ProductController extends AbstractController
{
    const NB_BLOGS_PER_PAGE = 12;

    /**
     * @Route("/magasin", name="magasin")
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {
        $produits = $this->getDoctrine()->getRepository(Produit::class)->findAll();
        $pagination = $paginator->paginate(
            $produits,
            $request->query->getInt('page', 1),
            self::NB_BLOGS_PER_PAGE
        );
        $categories = $this->getDoctrine()->getRepository(CategorieProduit::class)->findCategories();

        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'produits' => $pagination,
            'categories' => $categories
        ]);
    }

    /**
     * @Route("/magasin/recherche", name="magasin_search", methods={"GET","POST"})
     */
    public function magasinRecherche(Request $request)
    {
        $produits = $this->getDoctrine()->getRepository(Produit::class)->findBySearch($request->query->get('name'));
        $categories = $this->getDoctrine()->getRepository(CategorieProduit::class)->findCategories();

        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'produits' => $produits,
            'categories' => $categories
        ]);
    }

    /**
     * @Route("/magasin/categorie/{id}", name="categorie_produit")
     * @Entity("CategorieProduit", expr="repository.find(id)")
     */
    public function categorie(CategorieProduit $categorie)
    {
        $id = $categorie->getId();
        $categories = $this->getDoctrine()->getRepository(CategorieProduit::class)->findCategories();
        $produits = $this->getDoctrine()->getRepository(Produit::class)->findProduitsByCategorie($id);

        return $this->render('product/showByCategorie.html.twig', [
            'controller_name' => 'ProductController',
            'categorie' => $categorie,
            'categories' => $categories,
            'produits' => $produits
        ]);
    }

    /**
     * @Route("/magasin/sous-categorie/{id}", name="sous_categorie_produit")
     * @Entity("SousCategorieProduit", expr="repository.find(id)")
     */
    public function sous_categorie(SousCategorieProduit $souscategorie)
    {
        $id = $souscategorie->getId();
        $categories = $this->getDoctrine()->getRepository(CategorieProduit::class)->findCategories();
        $produits = $this->getDoctrine()->getRepository(Produit::class)->findProduitsBySousCategorie($id);

        return $this->render('product/showBySousCategorie.html.twig', [
            'controller_name' => 'ProductController',
            'categories' => $categories,
            'souscategorie' => $souscategorie,
            'produits' => $produits
        ]);
    }

    /**
     * @Route("/magasin/produit_{id}", name="magasin_produit")
     * @Entity("Produit", expr="repository.find(id)")
     */
    public function show(Produit $produit)
    {
        $categories = $this->getDoctrine()->getRepository(CategorieProduit::class)->findCategories();

        return $this->render('product/show.html.twig', [
            'controller_name' => 'ProductController',
            'categories' => $categories,
            'produit' => $produit
        ]);
    }

    /**
     * @Route("/admin/produits", name="admin_produits")
     */
    public function admin_show()
    {
        if ($this->getUser() != null && $this->getUser()->getUtilisateurType() == "admin") { // Si l'utilisateur est administrateur
            $repo = $this->getDoctrine()->getRepository(Produit::class);
            $produits = $repo->findAll();
            return $this->render('product/admin_show.html.twig', [
                'controller_name' => 'ProductController',
                'produits' => $produits
            ]);
        } else { // Sinon l'accès lui est refusé
            $this->addFlash('error', 'Vous avez un compte qui n\'est pas administrateur. Accès refusé.');
            return $this->redirectToRoute('home');
        }
    }

    /**
     * @Route("/admin/produit/add", name="ajouter_produit")
     * @Route("/admin/produit/{id}/edit", name="modifier_produit")
     */
    public function ajouterProduit(Produit $produit = null, Request $request, EntityManagerInterface $manager)
    {
        if ($this->getUser() != null && $this->getUser()->getUtilisateurType() == "admin") { // Si l'utilisateur est administrateur
            $editmode = true;
            if (!$produit) {
                $produit = new Produit();
                $editmode = false;
            }
            $form = $this->createFormBuilder($produit)
                ->add('Nomproduit', TextType::class, array('required' => true))
                ->add('PrixunitaireHT', NumberType::class, array('required' => true))
                ->add('TauxTVA', NumberType::class, array('required' => true))
                ->add('Presentation', TextType::class, array('required' => true))
                ->add('Descriptiondetaillee', TextareaType::class, array('required' => true))
                ->add('SousCategorieProduit', EntityType::class, [
                    'class' => SousCategorieProduit::class,
                    'choice_label' => 'Nom',
                    'required' => true,
                ])
                ->add('Image', FileType::class, [
                    'label' => 'Image',
                    'mapped' => false,
                    'required' => true,
                    'constraints' => [
                        new File([
                            'maxSize' => '2048k',
                            'mimeTypes' => [
                                "image/png",
                                "image/jpeg",
                                "image/jpg",
                                "image/gif",
                            ],
                            'mimeTypesMessage' => 'Uploadez un format d\'image valide (jpg, jped, png ou gif)'
                        ])
                    ],
                ])
                ->getForm();

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $ImageFile = $form->get('Image')->getData();
                $originalFilename = pathinfo($ImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename.'-'.uniqid().'.'.$ImageFile->guessExtension();
                $ImageFile->move(
                    $this->getParameter('image_produit_directory'),
                    $newFilename
                );
                $produit->setImage($newFilename);

                $manager->persist($produit);
                $manager->flush();
                return $this->redirectToRoute('admin_produits');
            }

            return $this->render('product/ajouterProduit.html.twig', [
                'controller_name' => 'ProductController',
                'formProduit' => $form->createView(),
                'editMode' => $editmode,
            ]);
        } else { // Sinon l'accès lui est refusé
            $this->addFlash('error', 'Vous avez un compte qui n\'est pas administrateur. Accès refusé.');
            return $this->redirectToRoute('home');
        }
    }

    /**
     * @Route("/admin/produit/{id}/delete", name="delete_produit")
     */
    public function deleteProduit(Produit $produit, EntityManagerInterface $manager)
    {
        if ($this->getUser() != null && $this->getUser()->getUtilisateurType() == "admin") { // Si l'utilisateur est administrateur
            $manager->remove($produit);
            $manager->flush();

            return $this->redirectToRoute('admin_produits');
        } else { // Sinon l'accès lui est refusé
            $this->addFlash('error', 'Vous avez un compte qui n\'est pas administrateur. Accès refusé.');
            return $this->redirectToRoute('home');
        }
    }
}

templates/product/admin_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit - Admin - {{ parent() }}{% endblock %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{ asset('../assets/admin.css') }}">

{% endblock %}

{% block body %}
    <div id="admin-produits">
        <h1>Page d'administration des produits</h1>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.nomProduit }}</td>
                <td>
                    <bouton onclick="window.location.href = '/admin/produit/{{ produit.id }}/edit';">
                        <i class="fa fa-pencil fa-2x"></i>
                    </bouton>
                    <bouton onclick="window.location.href = '/admin/produit/{{ produit.id }}/delete';">
                        <i class="fa fa-trash fa-2x"></i>
                    </bouton>
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <div class="btn" onclick="window.location.href = '{{ path('ajouter_produit') }}';">Ajouter un produit</div>
    </div>
{% endblock %}

templates/product/afficherCategorieProduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégories - Produit - Admin - {{ parent() }}{% endblock %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{asset('../assets/admin.css')}}">

{% endblock %}

{% block body %}
    <div id="admin-categories">
        <h1>Page d'administration des Catégories Produit</h1>
        <tbody>
        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.nom }}</td>
                <td>
                    <i class="fa fa-pencil fa-2x"
                       onclick="window.location.href = '/admin/produit/categorie/{{ categorie.id }}/edit';"></i>
                    <i class="fa fa-trash fa-2x"
                       onclick="window.location.href = '/admin/produit/categorie/{{ categorie.id }}/delete';"></i>
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <div class="btn" onclick="window.location.href = '{{ path('ajouter_categorie_produit') }}';">Ajouter un catégorie</div>
    </div>
{% endblock %}

templates/product/afficherSousCategorieProduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}SousCatégories - Produit - Admin - {{ parent() }}{% endblock %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{asset('../assets/admin.css')}}">

{% endblock %}

{% block body %}
    <div id="admin-sous-categories">
        <h1>Page d'administration des Sous-Categories Produit</h1>
        <tbody>
        {% for souscategorie in souscategories %}
            <tr>
                <td>{{ souscategorie.nom }}</td>
                <td>
                    <bouton onclick="window.location.href = '/admin/produit/souscategorie/{{ souscategorie.id }}/edit';">
                        <i class="fa fa-pencil fa-2x"></i>
                    </bouton>
                    <bouton onclick="window.location.href = '/admin/produit/souscategorie/{{ souscategorie.id }}/delete';">
                        <i class="fa fa-trash fa-2x"></i>
                    </bouton>
                </td>
            </tr>
        {% endfor %}
        <div class="btn" onclick="window.location.href = '{{ path('ajouter_souscategorie_produit') }}';">Ajouter une sous catégorie</div>
        </tbody>
    </div>
{% endblock %}

templates/product/ajouterCategorieProduit.html.twig
{% extends 'base.html.twig' %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{asset('../assets/admin.css')}}">

{% endblock %}

{% block body %}
    <div id="admin-add-categorie">
        {{ form_start(formCategorieProduit) }}

        {{ form_row(formCategorieProduit.nom, {'label' : 'Nom de la catégorie :','attr' : {'placeholder' : "catégorie"}}) }}
        {# {{ form_row(formCategorieProduit.UtilisateurAdmin, {'label' : 'utilisateur:','attr' : {'placeholder' : "utilisateur"}}) }} #}

        <button type="submit" class="btn btn-success ">
            {% if editMode %}
                Enregistrer les modifications
            {% else %}
                Ajouter la catégorie
            {% endif %}
        </button>

        {{ form(formCategorieProduit) }}
    </div>
{% endblock %}

templates/product/ajouterProduit.html.twig
{% extends 'base.html.twig' %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{asset('../assets/admin.css')}}">

{% endblock %}

{% block body %}
    <div id="admin-add-produit">
        {{ form_start(formProduit) }}

    {{ form_row(formProduit.Nomproduit, {'label' : 'Nom du produit :','attr' : {'placeholder' : "Nom"}}) }}
    {{ form_row(formProduit.PrixunitaireHT, {'label' : 'Prix unitaire HT :','attr' : {'placeholder' : "Prix HT"}}) }}
    {{ form_row(formProduit.TauxTVA, {'label' : 'Taux de TVA :','attr' : {'placeholder' : "Taux TVA du produit"}}) }}
    {{ form_row(formProduit.Presentation, {'label' : 'Présentation :','attr' : {'placeholder' :
        "Présentation brève du produit"}}) }}
    {{ form_row(formProduit.Descriptiondetaillee, {'label' : 'Description :','attr' : {'placeholder' :
        "Description détaillée du produit"}}) }}
    {{ form_row(formProduit.SousCategorieProduit, {'label' : 'sous catégorie :','attr' : {'placeholder' :
        "Sous-catégorie du produit"}}) }}
    {{ form_row(formProduit.Image,{'label' : 'Image du produit :'}
    ) }}
    <button type="submit" class="btn btn-success ">
        {% if editMode %}
            Enregistrer les modifications
        {% else %}
            Ajouter le produit
        {% endif %}
    </button>

        {{ form(formProduit) }}
    </div>
{% endblock %}

templates/product/ajouterSousCategorieProduit.html.twig
{% extends 'base.html.twig' %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{asset('../assets/admin.css')}}">

{% endblock %}

{% block body %}
    <div id="admin-add-sous-categorie">
        {{ form_start(formSousCategorieProduit) }}

        {{ form_row(formSousCategorieProduit.CategorieProduit, {'label' : 'Categorie :','attr' : {'placeholder' :
            "Categorie"}}) }}
        {{ form_row(formSousCategorieProduit.nom, {'label' : 'Nom de la sous categorie :','attr' : {'placeholder' :
            "Nom de la sous categorie"}}) }}

        <button type="submit" class="btn btn-success ">
            {% if editMode %}
                Enregistrer les modifications
            {% else %}
                Ajouter la sous-catégorie
            {% endif %}
        </button>

        {{ form(formSousCategorieProduit) }}
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% if produit is defined %}{{ produit.nomProduit }} {% endif %}- {{ parent() }}{% endblock %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{ asset('../assets/product/magasin.css') }}">

{% endblock %}

{% block body_before %}
<div id="menu-overlay" onclick="closeCategoryMenu()">
{% endblock %}

{% block body %}
    <form id="search-bar-magasin-container" class="row" action="{{ path('magasin_search') }}" method="get">
        <input id="search-bar-magasin" type="text" name="name" id="name" required placeholder="Rechercher">
        <button id="search-bar-magasin-button" type="submit" value="Rechercher">
            <i class="fa fa-search fa-lg"></i>
        </button>
    </form>

    <div id="accueil-magasin">
        <div class="produit-container col-sm-12">
            <div class="produit-subcontainer">
                <img class="image" src="{{ asset('../uploads/images/produits/'~ produit.image ) }}">

                <div id="details-produit">
                    <h1>{{ produit.nomProduit }}</h1>
                    <h5 class="text-center">{{ produit.SousCategorieProduit.categorieProduit.nom }}
                        - {{ produit.SousCategorieProduit.nom }}</h5>

                    <div id="details-prix-produit">
                        <div id="details-ht-produit">
                            <span class="details-produit-labels">Prix HT :</span> {{ produit.prixUnitaireHT }} € /
                            Unité
                        </div>
                        <div id="details-tva-produit">
                            <span class="details-produit-labels">TVA :</span> {{ produit.tauxTVA }} %
                        </div>
                        <div id="details-ttc-produit">
                            <span class="details-produit-labels">Prix TTC :</span> {{ (produit.prixUnitaireHT *
                            (1 + produit.tauxTVA / 100)) |round(2) }} € / Unité
                        </div>
                    </div>
                    <p id="desciption-details-produit">
                        <span class="details-produit-labels">Description :</span> {{ produit.descriptionDetaillee }}
                        <br/>
                    </p>
                </div>

                <div class="details-produit-achat-direct">
                    <input class="small-input" id="{{ produit.id }}" type="number" name="quantite" value=1>
                    <a id="{{ produit.id }}" class="bouton-ajout btn btn-success">
                        <i class="fa fa-shopping-cart mr-1"></i>Ajouter
                    </a>
                </div>
            </div>

        </div>

        <a id="open-menu-button" href="javascript:openCategoryMenu()" style="cursor:pointer">
            <i id="open-menu-button-icon" class="fa fa-caret-right fa-3x"></i>
        </a>

    </div>

{% endblock %}

{% block body_after %}
</div>
    <div id="categories-produits-container" class="sidenav">
        <a id="close-menu-button" href="javascript:closeCategoryMenu()" style="cursor:pointer">
            <i id="close-menu-button-icon" class="fa fa-caret-left fa-3x"></i>
        </a>
        <div id="categories-produits">
            <div id="accueil-magasin-link" class="categorie-produits">
                <a href="{{ path('magasin') }}">
                    <h4 class="categorie-produits-label">
                        Accueil magasin
                    </h4>
                </a>
            </div>
            {% for categ in categories %}
                <div id="{{ categ.id }}" class="categorie-produits">
                    <a data-toggle="collapse" data-parent="#categories-produits"
                       href="#sous-categories-{{ categ.id }}">
                        <h4 class="categorie-produits-label">
                            {{ categ.nom }}
                        </h4>
                    </a>
                    <div id="sous-categories-{{ categ.id }}" class="sous-categories-produits panel-collapse collapse">
                        <div id="self-{{ categ.id }}" class="sous-categorie-produits">
                            <a class="sous-categorie-produits-link"
                               href="{{ path('categorie_produit', {'id': categ.id }) }}">
                                <h6>Toute la catégorie</h6>
                            </a>
                        </div>
                        {% for souscateg in categ.sousCategorieProduits %}
                            <div id="sous-categorie-{{ souscateg.id }}" class="sous-categorie-produits">
                                <a class="sous-categorie-produits-link"
                                   href="{{ path('sous_categorie_produit', {'id': souscateg.id }) }}">
                                    <h6>{{ souscateg.nom }}</h6>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('.btn.btn-success').click(function () {
            let id = $(this).attr('id');
            let value = $("#" + id + "[name='quantite']").val();

            $.ajax({
                url: '/panier/ajouter/' + id,
                type: 'GET',
                data: {
                    quantite: value
                },
                dataType: "integer",
                success: function (response) {
                    // console.log(response);
                }
            });
            alert('Le produit a bien été ajouté au panier');
        });

        function openCategoryMenu() {
            document.getElementById("categories-produits-container").style.width = "330px";
            document.getElementById("categories-produits-container").style.paddingRight = "30px";
            document.getElementById("categories-produits").style.width = "300px";
            document.getElementById("categories-produits").style.border = "2px solid #555555dd";
            document.getElementById("categories-produits").style.borderLeft = "0";
            document.getElementById("close-menu-button").style.display = "block";
            document.getElementById("menu-overlay").style.zIndex = "10";
            document.getElementById("menu-overlay").style.opacity = "0.7";
        }

        function closeCategoryMenu() {
            document.getElementById("categories-produits-container").style.width = "0";
            document.getElementById("categories-produits-container").style.paddingRight = "0";
            document.getElementById("categories-produits").style.width = "0";
            document.getElementById("categories-produits").style.marginRight = "0";
            document.getElementById("categories-produits").style.border = "0";
            document.getElementById("close-menu-button").style.display = "none";
            document.getElementById("menu-overlay").style.zIndex = "5";
            document.getElementById("menu-overlay").style.opacity = "1";
        }

    </script>
{% endblock %}

templates/product/showBySousCategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sous-Catégorie {% if souscategorie is defined %}{{ souscategorie.nom }} {% endif %}- {{ parent() }}{% endblock %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{ asset('../assets/product/magasin.css') }}">

{% endblock %}

{% block body_before %}
<div id="menu-overlay" onclick="closeCategoryMenu()">
    {% endblock %}

    {% block body %}
        <form id="search-bar-magasin-container" class="row" action="{{ path('magasin_search') }}" method="get">
            <input id="search-bar-magasin" type="text" name="name" id="name" required placeholder="Rechercher">
            <button id="search-bar-magasin-button" type="submit" value="Rechercher">
                <i class="fa fa-search fa-lg"></i>
            </button>
        </form>

        <div class="navigation pag">
            {{ knp_pagination_render(produits) }}
        </div>

        <div id="accueil-magasin">

            <h1 class="text-center">{{ souscategorie.categorieProduit.nom }} - {{ souscategorie.nom }}</h1>

            <div id="products" class="row">
                {% if produits != [] %}
                    {% for produit in produits %}
                        <div class="produit-container col-lg-4 col-md-6 col-sm-12">
                            <a class="general-link" href="{{ path('magasin_produit', {'id' : produit.id}) }}">
                                <div class="produit-subcontainer">
                                    <img class="image" src="{{ asset('../uploads/images/produits/'~ produit.image ) }}">
                                    <p>{{ produit.presentation }}</p>
                                </div>
                                <div class="relative-subcontainer">
                                    <div class="produit-labels">
                                        <h5>{{ produit.nom_produit }}</h5>
                                        <p>{{ produit.prix_unitaire_ht }} € / Unité</p>
                                    </div>
                                    <div class="produit-achat-direct">
                                        <input class="small-input" id="{{ produit.id }}" type="number" name="quantite"
                                               value=1>
                                        <a id="{{ produit.id }}" class="bouton-ajout btn btn-success">
                                            <i class="fa fa-shopping-cart mr-1"></i>Ajouter
                                        </a>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    Aucun produit n'a été trouvé.
                {% endif %}
            </div>

            <a id="open-menu-button" href="javascript:openCategoryMenu()" style="cursor:pointer">
                <i id="open-menu-button-icon" class="fa fa-caret-right fa-3x"></i>
            </a>
        </div>

        <div class="navigation pag">
            {{ knp_pagination_render(produits) }}
        </div>

    {% endblock %}

    {% block body_after %}
</div>
    <div id="categories-produits-container" class="sidenav">
        <a id="close-menu-button" href="javascript:closeCategoryMenu()" style="cursor:pointer">
            <i id="close-menu-button-icon" class="fa fa-caret-left fa-3x"></i>
        </a>
        <div id="categories-produits">
            <div id="accueil-magasin-link" class="categorie-produits">
                <a href="{{ path('magasin') }}">
                    <h4 class="categorie-produits-label">
                        Accueil magasin
                    </h4>
                </a>
            </div>
            {% for categ in categories %}
                <div id="{{ categ.id }}" class="categorie-produits">
                    <a data-toggle="collapse" data-parent="#categories-produits"
                       href="#sous-categories-{{ categ.id }}">
                        <h4 class="categorie-produits-label">
                            {{ categ.nom }}
                        </h4>
                    </a>
                    <div id="sous-categories-{{ categ.id }}" class="sous-categories-produits panel-collapse collapse">
                        <div id="self-{{ categ.id }}" class="sous-categorie-produits">
                            <a class="sous-categorie-produits-link"
                               href="{{ path('categorie_produit', {'id': categ.id }) }}">
                                <h6>Toute la catégorie</h6>
                            </a>
                        </div>
                        {% for souscateg in categ.sousCategorieProduits %}
                            <div id="sous-categorie-{{ souscateg.id }}" class="sous-categorie-produits">
                                <a class="sous-categorie-produits-link"
                                   href="{{ path('sous_categorie_produit', {'id': souscateg.id }) }}">
                                    <h6>{{ souscateg.nom }}</h6>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('.btn.btn-success').click(function () {
            let id = $(this).attr('id');
            let value = $("#" + id + "[name='quantite']").val();

            $.ajax({
                url: '/panier/ajouter/' + id,
                type: 'GET',
                data: {
                    quantite: value
                },
                dataType: "integer",
                success: function (response) {
                    // console.log(response);
                }
            });
            alert('Le produit a bien été ajouté au panier');
        });

        function openCategoryMenu() {
            document.getElementById("categories-produits-container").style.width = "330px";
            document.getElementById("categories-produits-container").style.paddingRight = "30px";
            document.getElementById("categories-produits").style.width = "300px";
            document.getElementById("categories-produits").style.border = "2px solid #555555dd";
            document.getElementById("categories-produits").style.borderLeft = "0";
            document.getElementById("close-menu-button").style.display = "block";
            document.getElementById("menu-overlay").style.zIndex = "10";
            document.getElementById("menu-overlay").style.opacity = "0.7";
        }

        function closeCategoryMenu() {
            document.getElementById("categories-produits-container").style.width = "0";
            document.getElementById("categories-produits-container").style.paddingRight = "0";
            document.getElementById("categories-produits").style.width = "0";
            document.getElementById("categories-produits").style.marginRight = "0";
            document.getElementById("categories-produits").style.border = "0";
            document.getElementById("close-menu-button").style.display = "none";
            document.getElementById("menu-overlay").style.zIndex = "5";
            document.getElementById("menu-overlay").style.opacity = "1";
        }

    </script>
{% endblock %}