src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbArticles;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $montantTVA;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $montantHT;

    /**
     * @ORM\Column(type="float")
     */
    private $montantTotalTTC;

    /**
     * @ORM\Column(type="smallint")
     */
    private $isSend;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Produit")
     */
    private $Produit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PayPalID;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $shipping_addr;

    public function __construct()
    {
        $this->Produit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getNbArticles(): ?int
    {
        return $this->nbArticles;
    }

    public function setNbArticles(int $nbArticles): self
    {
        $this->nbArticles = $nbArticles;

        return $this;
    }

    public function getMontantTVA(): ?float
    {
        return $this->montantTVA;
    }

    public function setMontantTVA(?float $montantTVA): self
    {
        $this->montantTVA = $montantTVA;

        return $this;
    }

    public function getMontantHT(): ?float
    {
        return $this->montantHT;
    }

    public function setMontantHT(?float $montantHT): self
    {
        $this->montantHT = $montantHT;

        return $this;
    }

    public function getMontantTotalTTC(): ?float
    {
        return $this->montantTotalTTC;
    }

    public function setMontantTotalTTC(float $montantTotalTTC): self
    {
        $this->montantTotalTTC = $montantTotalTTC;

        return $this;
    }

    public function getIsSend(): ?int
    {
        return $this->isSend;
    }

    public function setIsSend(int $isSend): self
    {
        $this->isSend = $isSend;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduit(): Collection
    {
        return $this->Produit;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->Produit->contains($produit)) {
            $this->Produit[] = $produit;
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->Produit->contains($produit)) {
            $this->Produit->removeElement($produit);
        }

        return $this;
    }

    public function getPayPalID(): ?string
    {
        return $this->PayPalID;
    }

    public function setPayPalID(string $PayPalID): self
    {
        $this->PayPalID = $PayPalID;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->User;
    }

    public function setUser(?Utilisateur $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getShippingAddr(): ?string
    {
        return $this->shipping_addr;
    }

    public function setShippingAddr(string $shipping_addr): self
    {
        $this->shipping_addr = $shipping_addr;

        return $this;
    }
}

src/Controller/AchatController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Service\Panier\PanierService;
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\RedirectUrls;
use PayPal\Rest\ApiContext;
use PayPal\Api\Transaction;
use PayPal\Auth\OAuthTokenCredential;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGenerator;

class AchatController extends AbstractController
{
    protected $session;

    /**
     * @Route("/panier", name="panier")
     */
    public function index(PanierService $panierService)
    {
        if ($this->getUser() != null) { // Si l'utilisateur est connecté
            if ($this->getUser()->getUtilisateurType() != "pro") { // Si il n'a pas un compte pro on affiche le panier
                return $this->render('achat/index.html.twig', [
                    'controller_name' => 'AchatController',
                    'items' => $panierService->getPanierComplet(),
                    'total' => $panierService->getTotal()
                ]);
            } else { // Sinon on lui interdit
                $this->addFlash('error', 'Vous avez un compte entreprise. Accès refusé.');
                return $this->redirectToRoute('home');
            }
        } else { // Sinon on lui affiche le panier
            return $this->render('achat/index.html.twig', [
                'controller_name' => 'AchatController',
                'items' => $panierService->getPanierComplet(),
                'total' => $panierService->getTotal()
            ]);
        }
    }

    /**
     * @Route("/panier/paiement", name="panier_paiement")
     */
    public function paiement(PanierService $panierService)
    {
        if ($this->getUser() != null) { // Si l'utilisateur est connecté
            if ($this->getUser()->getUtilisateurType() != "pro") { // Si il n'a pas un compte pro on fait l'appel à l'API
                $credentials = [
                    'id' => 'Ae0q9Y6VL5tsv0vcBvzBMv3kjg7mM50yooD8C9u2nm1HmVa5pcCa9GH-Ov7swbpl1CHru_D2G_GXCQ4O',
                    'secret' => 'EFN_usuuBumAEyMgasVcamuZCaimCZ7JJzCWqsFbYKZ08HhQ6y43jENMHLJrk8qHhYfQRzXnt2SBYVHI'
                ];
                $apiContext = new ApiContext(
                    new OAuthTokenCredential($credentials['id'], $credentials['secret']
                    )
                );

                // On construit notre appel à l'API PayPal

                $list = new ItemList();
                $totalPrice = 0;
                foreach ($panierService->getPanierComplet() as $product) {
                    $item = (new Item())
                        ->setName($product['product']->getNomProduit())
                        ->setPrice(round($product['product']->getPrixUnitaireHT() * (1 + $product['product']->getTauxTVA() / 100), 2))
                        ->setCurrency('EUR')
                        ->setQuantity($product['quantity']);
                    $list->addItem($item);

                    $totalPrice += ($product['quantity'] * round(($product['product']->getPrixUnitaireHT() * (1 + $product['product']->getTauxTVA() / 100)), 2));
                }
                $details = (new Details())
                    ->setSubtotal($totalPrice);

                $amount = (new Amount())
                    ->setTotal($totalPrice)
                    ->setCurrency('EUR')
                    ->setDetails($details);

                $transaction = (new Transaction())
                    ->setItemList($list)
                    ->setDescription('Achat sur le site Eco-Service')
                    ->setAmount($amount);

                $payment = new Payment();
                $payment->setTransactions([$transaction]);
                $payment->setIntent('sale');
                $redirectUrls = (new RedirectUrls())
                    ->setReturnUrl($this->generateUrl('panier_paiement_termine', [], UrlGenerator::ABSOLUTE_URL))
                    ->setCancelUrl($this->generateUrl('panier', [], UrlGenerator::ABSOLUTE_URL));
                $payment->setRedirectUrls($redirectUrls);
                $payment->setPayer((new Payer())->setPaymentMethod('paypal'));

                try {
                    $payment->create($apiContext);
                    header('Location: '.$payment->getApprovalLink());
                } catch (\PayPal\Exception\PayPalConnectionException $e) {
                    dump(json_decode($e->getData()));
                }
                return $this->render('achat/showCommande.html.twig', [
                    'controller_name' => 'AchatController',
                ]);
            } else { // Sinon on lui refuse l'accès
                $this->addFlash('error', 'Vous avez un compte entreprise. Accès refusé.');
                return $this->redirectToRoute('home');
            }
        } else { // Sinon on lui demande de se connecter
            $this->addFlash('error', 'Veuillez vous connecter pour effectuer une commande.');
            return $this->redirectToRoute('security_login');
        }
    }

    /**
     * @Route("/panier/paiement_termine", name="panier_paiement_termine")
     */
    public function paiementTermine(Request $request, PanierService $panier)
    {
        ///////////// Exécution du paiement PayPal

        $credentials = [
            'id' => 'Ae0q9Y6VL5tsv0vcBvzBMv3kjg7mM50yooD8C9u2nm1HmVa5pcCa9GH-Ov7swbpl1CHru_D2G_GXCQ4O',
            'secret' => 'EFN_usuuBumAEyMgasVcamuZCaimCZ7JJzCWqsFbYKZ08HhQ6y43jENMHLJrk8qHhYfQRzXnt2SBYVHI'
        ];
        $apiContext = new ApiContext(
            new OAuthTokenCredential($credentials['id'], $credentials['secret']
            )
        );
        $payment = Payment::get($quantite = $request->get('paymentId'), $apiContext);

        $execution = (new PaymentExecution())
            ->setPayerId($request->get('PayerID'))
            ->setTransactions($payment->getTransactions());
        try {
            $payment->execute($execution, $apiContext);
        } catch (\PayPal\Exception\PayPalConnectionException $e) {
            dump(json_decode($e->getData()));
        }

        ///////////// Insertion de la commande en BDD

        $entityManager = $this->getDoctrine()->getManager();
        $commande = new Commande();

        $montantHT = 0;
        $montantTVA = 0;
        $nbArticles = 0;
        foreach ($panier->getPanierComplet() as $item) {
            for ($i = 0; $i < $item['quantity']; $i++) {
                $montantHT += $item['product']->getPrixUnitaireHT();
                $montantTVA += (($item['product']->getTauxTVA() / 100) * $item['product']->getPrixUnitaireHT());
                $nbArticles++;
                $commande->addProduit($item['product']);
            }
        }

        $adresse = $payment->getPayer()->getPayerInfo()->getShippingAddress();

        $commande->setDate(new \DateTime());
        $commande->setIsSend(0);
        $commande->setMontantHT($montantHT);
        $commande->setMontantTVA($montantTVA);
        $commande->setMontantTotalTTC($montantHT + $montantTVA);
        $commande->setNbArticles($nbArticles);
        $commande->setPayPalID($payment->id);
        $commande->setUser($this->getUser());
        $commande->setShippingAddr($adresse->getLine1().'|'.$adresse->getLine2().'|'.$adresse->getPostalCode().'|'.$adresse->getCity());
        $entityManager->persist($commande);
        $entityManager->flush();

        ///////////// Réinitialisation du panier

        $panier->reset();

        return $this->render('achat/showCommande.html.twig', [
            'controller_name' => 'AchatController',
            'commande' => $commande,
            'adresse' => explode('|', $commande->getShippingAddr()),
        ]);
    }

    /**
     * @Route("/panier/ajouter/{id}", name="panier_add", methods={"GET","HEAD"})
     */
    public function add(Request $request, $id, PanierService $panierService)
    {
        $quantite = $request->get('quantite');

        for ($i = 0; $i < $quantite; $i++) {
            $panierService->add($id);
        }

        return $this->redirectToRoute("panier");
    }

    /**
     * @Route("/panier/supprimer/{id}", name="panier_remove")
     */
    public function remove($id, PanierService $panierService)
    {
        $panierService->remove($id);

        return $this->redirectToRoute("panier");
    }
}

templates/achat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier - {{ parent() }}{% endblock %}

{% block additional_stylesheets %}

    <link rel="stylesheet" type="text/css" href="{{ asset('../assets/achat/panier.css') }}">

{% endblock %}

{% block body %}
    <div class="p-3">
        <h1>Votre panier</h1>
    </div>

    {% if items | length > 0 %}
        <table id="table-produits-panier">
            <thead id="produits-panier-header">
            <tr>
                <th width="20%">Produit</th>
                <th width="80%">Informations et Quantité</th>
            </tr>
            </thead>
            <tbody id="produits-panier-body">
            {% for item in items %}
                <tr>
                    <td>
                        <div class="nom-produit-panier">
                            <p>{{ item.product.nomProduit }}</p>
                        </div>
                    </td>
                    <td>
                        <div class="infos-produit-panier row d-flex">
                            <div class="prix-unitaire-produit col-sm-12 col-md-2">
                                <p>
                                    {{ (((item.product.prixUnitaireHT * (1 + item.product.tauxTVA / 100))|round(2))|number_format(2)) }}
                                    € / unité
                                </p>
                            </div>
                            <div class="quantite-produit col-sm-12 col-md-10 row">
                                <input class="quantite-produit-input" id="{{ item.product.id }}" type="number"
                                       name="quantite" value={{ item.quantity }}>
                                <a class="bouton-update quantite-produit-refresh btn btn-success update"
                                   id="{{ item.product.id }}"><i class="fa fa-shopping-cart mr-1"></i> Mettre à jour le
                                    panier</a>
                                <div class="bouton-suppression-produit">
                                    <a href="{{ path('panier_remove', {'id': item.product.id}) }}"
                                       class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </div>

                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div id="produits-panier-foot">
            <h5 colspan="3" class="text-right">
                Total : {{ (((total)|round(2))|number_format(2)) }}€
            </h5>
        </div>

        <a class="quantite-produit-refresh" href="{{ path('panier') }}">Mettre à jour le total</a>
        <a href="{{ path('panier_paiement') }}" class="quantite-produit-refresh"><i class="fa fa-paypal"></i> Payer</a>

        <div id="emptyspace" style="height:150px">

        </div>
    {% else %}
        <p>Votre panier est vide.</p>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('.btn.btn-success.update').click(function () {
            let id = $(this).attr('id');
            let value = $("#" + id + "[name='quantite']").val();

            $.ajax({
                url: '/panier/supprimer/' + id,
                type: 'GET',
                data: {
                    quantite: value
                },
                dataType: "integer",
                success: function (response) {

                }
            });
            $.ajax({
                url: '/panier/ajouter/' + id,
                type: 'GET',
                data: {
                    quantite: value
                },
                dataType: "integer",
                success: function (response) {
                    // console.log(response);
                }
            });

            alert('La quantité a bien été mise à jour');
        });
    </script>
{% endblock %}

templates/achat/paiement.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement -
    {{ parent() }}
{% endblock %}

{% block body %}
    Si vous voyez ce message, ce n'est pas normal. Merci de retourner sur le magasin et de nous signaler cela.
{% endblock %}

templates/achat/showCommande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande {% if commande is defined %}n°{{ commande.id }} {% endif %}- {{ parent() }}{% endblock %}

{% block additional_stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('../assets/Adresse/adresse.css')}}">
{% endblock %}

{% block body %}
    {% if commande is defined %}
        <div class="container-commande">
            <h1>Récapitulatif de votre commande numéro {{ commande.id }}</h1>

            
            <div class="item-commande"><p>Nom de l'utilisateur : </p><p class="result"> {{ commande.user.prenom }} {{ commande.user.nom }}</p></div>
            <div class="item-commande"><p>ID PayPal de la commande : </p><p class="result">{{ commande.paypalid }}</p></div>
            <div class="item-commande"><p>Date de la commande : le </p><p class="result">{{ commande.date | date("d/m/Y") }}</p></div>
            <div class="item-commande"><p>Etat de la commande :   </p><p class="result">{% if commande.isSend == -1 %}
                                        annulée
                                    {% else %}
                                        {% if commande.isSend == 0 %}
                                            en attente de traitement
                                        {% else %}
                                            {% if commande.isSend == 1 %}
                                                envoyée
                                            {% else %}
                                                statut inconnu
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
            </p></div>
            <div class="item-commande">
            <p>Adresse de livraison :</p>
            <p class="result">
            {% for adresse in adresse %}
                {{ adresse }} 
            {% endfor %}
            </p>
            </div>
            <div class="item-commande"><p>Nombre d'articles : </p><p class="result"> {{ commande.nbArticles }} </p></div>
            <div class="item-commande"><p>Montant HT : </p><p class="result"> {{ commande.montantHT }}€ </p></div>
            <div class="item-commande"><p>Montant TVA : </p><p class="result"> {{ commande.montantTVA }}% </p></div>
            <div class="item-commande"><p>Montant TTC : </p><p class="result"> {{ commande.montantTotalTTC }}€ </p></div>
            
            <table class="table">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix HT</th>
                        <th>TVA</th>
                        <th>Prix TTC</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in commande.produit %}
                        <tr>
                            <td>{{ item.nomProduit }}</td>
                            <td>{{ item.prixUnitaireHT }}€</td>
                            <td>{{ item.tauxTVA }}%</td>
                            <td>{{ item.prixUnitaireHT * (1 + item.tauxTVA / 100) |round(2)}}€</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="text-right"> Montant total :</td>
                        <td>{{ commande.montantTotalTTC }}€</td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    {% else %}
        Impossible d'afficher la commande.
    {% endif %}

{% endblock %}